### ISSUE TITLE
Does not work with `serverless-plugin-split-stacks`

### ISSUE THREAD

**Issue by thisjeremiah** [awslabs/aws-amplify-serverless-plugin#44]
Looks like this plugin does not work with [`serverless-plugin-split-stacks`](https://github.com/dougmoscrop/serverless-plugin-split-stacks), a suggested plugin by [`serverless-appsync-plugin`](https://github.com/sid88in/serverless-appsync-plugin) to solve the 200 CF resource limit.

I get the error message:
```
ERROR: amplify-plugin: Cannot load resources: No GraphQL API found - cannot write schema.json file
```

And if I use `SLS_DEBUG=*`, I can see that the nested stacks are being skipped:

```
amplify-plugin: Skipping {"LogicalResourceId":"AppSyncNestedStack","PhysicalResourceId":"arn:aws:cloudformation:us-west-2:*:stack/*-AppSyncNestedStack-*/*",
"ResourceType":"AWS::CloudFormation::Stack","LastUpdatedTimestamp":"2019-01-15T18:39:25.317Z","ResourceStatus":"UPDATE_COMPLETE","DriftInformation":{"StackResourceDriftStatus":"NOT_CHECKED"}}
```

Perhaps the fix could be to recursively check the nested stacks?

**Comment by adrianhall** [comment]
Thanks for this.  I see the PR for this as well, and will process.
