### ISSUE TITLE
BUG: error when running example (PR submitted)

### ISSUE THREAD

**Issue by rayjanwilson** [awslabs/aws-amplify-serverless-plugin#9]
when running the provided example, the following error is thrown:
```bash
ERROR: amplify-plugin: Writing to examples/awsconfiguration.json: Error: ENOENT: no such file or directory, open 'examples/awsconfiguration.json'
ERROR: amplify-plugin: Writing to examples/schema.json: Error: ENOENT: no such file or directory, open 'examples/schema.json'
ERROR: amplify-plugin: Writing to examples/aws-exports.js: Error: ENOENT: no such file or directory, open 'examples/aws-exports.js'
```

*Pull Request incoming*

- A reproducible test case or series of steps
  - clone repo and cd into directory
  - `npm install`
  - `cd example`
  - `npm install`
  - `npm run deploy`
- The version of our code being used
  - v0.1.0
- Any modifications you've made relevant to the bug
  - direct clone from github
- Anything unusual about your environment or deployment
  - os x: v10.13.6
  - serverless: v1.32.0
  - node.js: v10.12.0

**Comment by rayjanwilson** [comment]
gotcha makes sense

**Comment by adrianhall** [comment]
Checkin #a80856e fixes this issue.
